### ISSUE TITLE
No values shown anymore

### ISSUE THREAD

**Issue by JustThe2ofUs** [biemond/com.athom.awair#6]
See title;
No values are shown anymore, see screenshot. 
![18EB6648-EB48-410F-8DE9-22F07C8897F5](https://user-images.githubusercontent.com/45788142/69914956-10c98880-144a-11ea-89cf-a373e9623b8e.png)

Where is it all gone? 🤔🤷‍♂️

**Comment by biemond** [comment]
Hi,  

because of the new out of the box value triggers, I had to rename a lot of measurements.  Can you try to re-install the device.  I added it to change release notes

But if you are already did this , maybe there is something with the api key.  you can send me your api key and I will check it in postman, maybe you are blocked or so.

**Comment by JustThe2ofUs** [comment]
Re-adding already did the trick. Thx m8!
